import './globals.css'
import type { Metadata } from 'next'
import { Poppins, Nunito_Sans } from 'next/font/google'

const poppin = Poppins({ 
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'] 
})

const nunito_sans = Nunito_Sans({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-nunito-sans'
})

export const metadata: Metadata = {
  title: 'TOTC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className={`${nunito_sans.variable}`}>
      <body className={poppin.className}>{children}</body>
    </html>
  )
}
